-- LISTA DOS CURSOS COM NOME DA CATEGORIA E DO INSTRUTOR
SELECT
	C.TITULO AS CURSO,
	C.DESCRICAO AS DESCRICAO_CURSO,
	CA.nome AS CATEGORIA,
	I.NOME AS INSTRUTOR
FROM
	"EDUTECH".DBO.CURSOS C
	LEFT JOIN "EDUTECH".DBO.CATEGORIAS CA
		ON CA.ID = C.ID_CATEGORIA
	LEFT JOIN "EDUTECH".DBO.INSTRUTORES I
		ON I.ID = C.ID_INSTRUTOR AND I.ativo = TRUE
;


-- LISTAR TODOS OS ALUNOS MATRICULADOS EM UM CURSO ESPECIFICO
SELECT DISTINCT
	C.TITULO AS CURSO,
	A.NOME AS ALUNO,
	A.EMAIL AS ALUNO_EMAIL
FROM
	"EDUTECH".DBO.CURSOS C
	JOIN "EDUTECH".DBO.MATRICULAS M
		ON M.ID_CURSO = C.ID
	JOIN "EDUTECH".DBO.ALUNOS A
		ON A.ID = M.ID_ALUNO
WHERE
	A.ATIVO = TRUE
	AND M.ID_STATUS = 1
	AND M.DATA_CONCLUSAO IS NULL
ORDER BY
	C.TITULO,
	A.NOME
;


-- EXIBIR TODAS AS AULAS DE UM CURSO ORDENADAS POR MODULO E ORDEM
SELECT
	C.TITULO AS CURSO,
	M.ORDEM AS ORDEM_MODULO,
	M.TITULO AS MODULO,
	A.ORDEM AS ORDEM_AULA,
	A.TITULO AS AULA
FROM
	"EDUTECH".DBO.CURSOS C
	JOIN "EDUTECH".DBO.MODULOS M
		ON M.ID_CURSO = C.ID
	JOIN "EDUTECH".DBO.AULAS A
		ON A.ID_MODULO = M.ID
ORDER BY
	C.ID,
	M.ordem,
	A.ordem
;


-- MEDIA DAS AVALIACOES DOS CURSOS
SELECT
	C.TITULO AS CURSO,
	COUNT(A.ID) AS QUANTIDADE_AVALIACOES,
	AVG(A.NOTA)::DECIMAL(10,2) AVALIACAO_MEDIA
FROM
	"EDUTECH".DBO.CURSOS C
	JOIN "EDUTECH".DBO.AVALIACOES A
		ON A.ID_CURSO = C.ID
GROUP BY
	C.TITULO
;


-- QUANTIDADE DE ALUNOS MATRICULADOS POR CURSO
SELECT
	C.TITULO AS CURSO,
	COUNT(M.ID_ALUNO) QUANTIDADE_ALUNOS
FROM
	"EDUTECH".DBO.CURSOS C
	JOIN "EDUTECH".DBO.MATRICULAS M
		ON M.ID_CURSO = C.ID
	JOIN "EDUTECH".DBO.ALUNOS A
		ON A.ID = M.ID_ALUNO
WHERE
	M.data_conclusao IS NULL
	AND M.ID_STATUS = 1
	AND A.ATIVO = TRUE
GROUP BY 
	C.TITULO
;


-- FATURAMENTO TOTAL POR CATEGORIA
SELECT
	CA.NOME AS CATEGORIA,
	COALESCE(SUM(M.VALOR_PAGO), 0)::DECIMAL(10,2) AS FATURAMENTO_TOTAL
FROM
	"EDUTECH".DBO.CATEGORIAS CA
	LEFT JOIN "EDUTECH".DBO.CURSOS C
		ON C.ID_CATEGORIA = CA.ID
	LEFT JOIN "EDUTECH".DBO.MATRICULAS M
		ON M.ID_CURSO = C.ID
GROUP BY
	CA.NOME
;


-- CURSO COM MAIOR NUMERO DE MATRICULAS ATIVAS
SELECT
	C.TITULO AS CURSO,
	COUNT(M.ID) AS QUANTIDADE_MATRICULAS
FROM
	"EDUTECH".DBO.CURSOS C
	JOIN "EDUTECH".DBO.MATRICULAS M
		ON M.ID_CURSO = C.ID
WHERE
	M.ID_STATUS = 1
GROUP BY
	C.TITULO
ORDER BY
	COUNT(M.ID) DESC
LIMIT 1
;


-- LISTA DE ALUNOS COM PERCENTUAL DE CONCLUSAO NOS CURSOS MATRICULADOS
SELECT
	A.NOME,
	C.TITULO AS CURSO,
	SUM(P.TEMPO_ASSISTIDO) AS TEMPO_TOTAL_ASSISTIDO,
	C.CARGA_HORARIA,
	(CAST(SUM(P.TEMPO_ASSISTIDO) AS FLOAT) / C.CARGA_HORARIA * 100)::DECIMAL(10,2) AS PERCENTUAL_CONCLUSAO
FROM
	"EDUTECH".DBO.ALUNOS A
	JOIN "EDUTECH".DBO.MATRICULAS M
		ON M.ID_ALUNO = A.ID
	JOIN "EDUTECH".DBO.CURSOS C
		ON C.ID = M.ID_CURSO
	JOIN "EDUTECH".DBO.PROGRESSO_AULAS P
		ON P.ID_MATRICULA = M.ID
WHERE
	A.ATIVO = TRUE
	AND M.ID_STATUS <> 3
GROUP BY
	A.NOME,
	C.TITULO,
	C.CARGA_HORARIA
;


-- Relatório completo de um curso: instrutor, número de alunos, média de avaliações, faturamento
SELECT
	C.TITULO AS CURSO,
	CA.NOME AS CATEGORIA,
	COALESCE(I.NOME, '-- INSTRUTOR NÃO CADASTRADO --') AS INSTRUTOR_ATUAL,
	COUNT(DISTINCT A.ID) AS QTD_TOTAL_ALUNOS,
	AVG(AV.NOTA)::DECIMAL(10,2) AS MEDIA_AVALIACOES,
	COALESCE(SUM(M.VALOR_PAGO), 0)::DECIMAL(10,2) AS FATURAMENTO_TOTAL
FROM
	"EDUTECH".DBO.CURSOS C
	LEFT JOIN "EDUTECH".DBO.CATEGORIAS CA
		ON CA.ID = C.ID_CATEGORIA
	LEFT JOIN "EDUTECH".DBO.INSTRUTORES I
		ON I.ID = C.ID_INSTRUTOR AND I.ATIVO = TRUE
	LEFT JOIN "EDUTECH".DBO.MATRICULAS M
		ON M.ID_CURSO = C.ID
	LEFT JOIN "EDUTECH".DBO.ALUNOS A
		ON A.ID = M.ID_ALUNO
	LEFT JOIN "EDUTECH".DBO.AVALIACOES AV
		ON AV.ID_CURSO = C.ID AND AV.ID_MATRICULA = M.ID
GROUP BY
	C.TITULO,
	CA.NOME,
	I.NOME
;


-- Listar instrutores com quantidade de cursos, total de alunos e média geral de avaliações
SELECT
	I.NOME AS INSTRUTOR,
	COUNT(DISTINCT C.ID) AS QTD_CURSOS,
	COUNT(DISTINCT M.ID_ALUNO) AS QTD_ALUNOS,
	AVG(A.NOTA)::DECIMAL(10,2) AS MEDIA_AVALIACOES
FROM
	"EDUTECH".DBO.INSTRUTORES I
	LEFT JOIN "EDUTECH".DBO.CURSOS C
		ON C.ID_INSTRUTOR = I.ID
	LEFT JOIN "EDUTECH".DBO.MATRICULAS M
		ON M.ID_CURSO = C.ID
	LEFT JOIN "EDUTECH".DBO.AVALIACOES A
		ON A.ID_CURSO = C.ID AND A.ID_MATRICULA = M.ID
WHERE
	I.ATIVO = TRUE
GROUP BY
	I.NOME
;


-- Top 5 cursos mais rentáveis
SELECT
	C.TITULO AS CURSO,
	COALESCE(SUM(M.VALOR_PAGO), 0)::DECIMAL(10,2) AS FATURAMENTO_TOTAL
FROM
	"EDUTECH".DBO.CURSOS C
	LEFT JOIN "EDUTECH".DBO.MATRICULAS M
		ON M.ID_CURSO = C.ID
GROUP BY
	C.TITULO
ORDER BY
	SUM(M.VALOR_PAGO) DESC
LIMIT 5
;


-- Alunos que não concluíram nenhum curso nos últimos 6 meses
SELECT DISTINCT
	A.NOME AS ALUNO
FROM
	"EDUTECH".DBO.ALUNOS A
	LEFT JOIN "EDUTECH".DBO.MATRICULAS M
		ON M.ID_ALUNO = A.ID
WHERE
	A.ATIVO = TRUE
	AND (
		M.DATA_CONCLUSAO IS NULL
		OR M.DATA_CONCLUSAO < (CURRENT_DATE - INTERVAL '6 months')::DATE
	)
ORDER BY
	A.NOME
;
