-- CRIACAO DO BANCO DE DADOS
CREATE DATABASE EDUTECH;

-- CRIACAO DO SCHEMA
CREATE SCHEMA IF NOT EXISTS DBO;


-- CRIACAO DAS TABELAS

-- CRIACAO DA TABELA DE ALUNOS
CREATE TABLE "EDUTECH".DBO.ALUNOS (
    ID SERIAL PRIMARY KEY NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    ATIVO BOOLEAN DEFAULT TRUE NOT NULL,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

COMMENT ON COLUMN "EDUTECH".DBO.ALUNOS.ID IS 'Identificador único do aluno';
COMMENT ON COLUMN "EDUTECH".DBO.ALUNOS.NOME IS 'Nome do aluno';
COMMENT ON COLUMN "EDUTECH".DBO.ALUNOS.EMAIL IS 'Email de login do aluno';
COMMENT ON COLUMN "EDUTECH".DBO.ALUNOS.DATA_NASCIMENTO IS 'Data de nascimento do aluno';
COMMENT ON COLUMN "EDUTECH".DBO.ALUNOS.ATIVO IS 'Indica se o aluno está ativo ou não';
COMMENT ON COLUMN "EDUTECH".DBO.ALUNOS.DATA_CADASTRO IS 'Data de cadastro do aluno';

-- CRICAO DA TABELA DE ESPECIALIDADE DOS INSTRUTORES
CREATE TABLE "EDUTECH".DBO.ESPECIALIDADES (
    ID SERIAL PRIMARY KEY NOT NULL,
    ESPECIALIDADE VARCHAR(50) UNIQUE NOT NULL
);

COMMENT ON COLUMN "EDUTECH".DBO.ESPECIALIDADES.ID IS 'Identificador único da especialidade';
COMMENT ON COLUMN "EDUTECH".DBO.ESPECIALIDADES.ESPECIALIDADE IS 'Nome da especialidade';

-- CRIACAO DA TABELA DE INSTRUTORES
CREATE TABLE "EDUTECH".DBO.INSTRUTORES (
    ID SERIAL PRIMARY KEY NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    BIOGRAFIA TEXT NULL,
    ATIVO BOOLEAN DEFAULT TRUE NOT NULL,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

COMMENT ON COLUMN "EDUTECH".DBO.INSTRUTORES.ID IS 'Identificador único do instrutor';
COMMENT ON COLUMN "EDUTECH".DBO.INSTRUTORES.NOME IS 'Nome do instrutor';
COMMENT ON COLUMN "EDUTECH".DBO.INSTRUTORES.EMAIL IS 'Email de login do instrutor';
COMMENT ON COLUMN "EDUTECH".DBO.INSTRUTORES.BIOGRAFIA IS 'Biografia do instrutor';
COMMENT ON COLUMN "EDUTECH".DBO.INSTRUTORES.ATIVO IS 'Indica se o instrutor está ativo ou não';
COMMENT ON COLUMN "EDUTECH".DBO.INSTRUTORES.DATA_CADASTRO IS 'Data de cadastro do instrutor';

-- CRIACAO DA TABELA PARA RELACIONAMENTO N:M DE ESPECIALIDADE DOS INSTRUTORES
CREATE TABLE "EDUTECH".DBO.ESPECIALIDADES_INSTRUTORES (
    ID_ESPECIALIDADE INT NOT NULL,
    ID_INSTRUTOR INT NOT NULL,
    FOREIGN KEY (ID_ESPECIALIDADE) REFERENCES "EDUTECH".DBO.ESPECIALIDADES(ID),
    FOREIGN KEY (ID_INSTRUTOR) REFERENCES "EDUTECH".DBO.INSTRUTORES(ID),
    PRIMARY KEY (ID_ESPECIALIDADE, ID_INSTRUTOR)
);

COMMENT ON COLUMN "EDUTECH".DBO.ESPECIALIDADES_INSTRUTORES.ID_ESPECIALIDADE IS 'Identificador da especialidade';
COMMENT ON COLUMN "EDUTECH".DBO.ESPECIALIDADES_INSTRUTORES.ID_INSTRUTOR IS 'Identificador do instrutor';

-- CRIACAO DA TABELA DE CATEGORIAS DOS CURSOS
CREATE TABLE "EDUTECH".DBO.CATEGORIAS (
    ID SERIAL PRIMARY KEY NOT NULL,
    NOME VARCHAR(50) NOT NULL UNIQUE,
    DESCRICAO VARCHAR(200) NULL,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

COMMENT ON COLUMN "EDUTECH".DBO.CATEGORIAS.ID IS 'Identificador único da categoria';
COMMENT ON COLUMN "EDUTECH".DBO.CATEGORIAS.NOME IS 'Nome da categoria';
COMMENT ON COLUMN "EDUTECH".DBO.CATEGORIAS.DESCRICAO IS 'Descrição da categoria';
COMMENT ON COLUMN "EDUTECH".DBO.CATEGORIAS.DATA_CADASTRO IS 'Data de cadastro da categoria';


-- CRIACAO DA TABELA DE NIVEIS DO CURSO
CREATE TABLE "EDUTECH".DBO.CURSOS_NIVEL (
    ID SERIAL PRIMARY KEY NOT NULL,
    NIVEL VARCHAR(20) UNIQUE NOT NULL
);

COMMENT ON COLUMN "EDUTECH".DBO.CURSOS_NIVEL.ID IS 'Identificador único do nível do curso';
COMMENT ON COLUMN "EDUTECH".DBO.CURSOS_NIVEL.NIVEL IS 'Nome do nível do curso';


-- CRIACAO DA TABELA DE CURSOS
CREATE TABLE "EDUTECH".DBO.CURSOS (
    ID SERIAL PRIMARY KEY NOT NULL,
    TITULO VARCHAR(100) NOT NULL,
    DESCRICAO TEXT NULL,
    PRECO FLOAT DEFAULT 0 NOT NULL,
    CARGA_HORARIA INT NOT NULL,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ID_NIVEL INT NOT NULL,
    ID_INSTRUTOR INT NULL,
    ID_CATEGORIA INT NULL,
    FOREIGN KEY (ID_NIVEL) REFERENCES "EDUTECH".DBO.CURSOS_NIVEL(ID),
    FOREIGN KEY (ID_INSTRUTOR) REFERENCES "EDUTECH".DBO.INSTRUTORES(ID),
    FOREIGN KEY (ID_CATEGORIA) REFERENCES "EDUTECH".DBO.CATEGORIAS(ID)
  );


COMMENT ON COLUMN "EDUTECH".DBO.CURSOS.ID IS 'Identificador único do curso';
COMMENT ON COLUMN "EDUTECH".DBO.CURSOS.TITULO IS 'Título do curso';
COMMENT ON COLUMN "EDUTECH".DBO.CURSOS.DESCRICAO IS 'Descrição do curso';
COMMENT ON COLUMN "EDUTECH".DBO.CURSOS.PRECO IS 'Preço do curso';
COMMENT ON COLUMN "EDUTECH".DBO.CURSOS.CARGA_HORARIA IS 'Carga horária do curso em minutos';
COMMENT ON COLUMN "EDUTECH".DBO.CURSOS.DATA_CADASTRO IS 'Data de cadastro do curso';
COMMENT ON COLUMN "EDUTECH".DBO.CURSOS.ID_NIVEL IS 'Identificador do nível do curso';
COMMENT ON COLUMN "EDUTECH".DBO.CURSOS.ID_INSTRUTOR IS 'Identificador do instrutor do curso';
COMMENT ON COLUMN "EDUTECH".DBO.CURSOS.ID_CATEGORIA IS 'Identificador da categoria do curso';


-- CRIACAO DA TABELA DE MODULOS
CREATE TABLE "EDUTECH".DBO.MODULOS (
    ID SERIAL PRIMARY KEY NOT NULL,
    TITULO VARCHAR(50) NOT NULL,
    DESCRICAO TEXT NULL,
    ORDEM INT NOT NULL,
    ID_CURSO INT NOT NULL,
    FOREIGN KEY (ID_CURSO) REFERENCES "EDUTECH".DBO.CURSOS(ID)
);

COMMENT ON COLUMN "EDUTECH".DBO.MODULOS.ID IS 'Identificador único do módulo';
COMMENT ON COLUMN "EDUTECH".DBO.MODULOS.TITULO IS 'Título do módulo';
COMMENT ON COLUMN "EDUTECH".DBO.MODULOS.DESCRICAO IS 'Descrição do módulo';
COMMENT ON COLUMN "EDUTECH".DBO.MODULOS.ORDEM IS 'Ordem do módulo no curso';
COMMENT ON COLUMN "EDUTECH".DBO.MODULOS.ID_CURSO IS 'Identificador do curso ao qual o módulo pertence';


-- CRIACAO DA TABELA DE TIPOS DE AULA
CREATE TABLE "EDUTECH".DBO.AULAS_TIPO (
    ID SERIAL PRIMARY KEY NOT NULL,
    TIPO VARCHAR(20) UNIQUE NOT NULL
);

COMMENT ON COLUMN "EDUTECH".DBO.AULAS_TIPO.ID IS 'Identificador único do tipo de aula';
COMMENT ON COLUMN "EDUTECH".DBO.AULAS_TIPO.TIPO IS 'Nome do tipo de aula';


-- CRIACAO DA TABELA DE AULAS
CREATE TABLE "EDUTECH".DBO.AULAS (
    ID SERIAL PRIMARY KEY NOT NULL,
    TITULO VARCHAR(100) NOT NULL,
    DURACAO INT NOT NULL,
    ORDEM INT NOT NULL,
    ID_TIPO INT NOT NULL,
    ID_MODULO INT NOT NULL,
    FOREIGN KEY (ID_TIPO) REFERENCES "EDUTECH".DBO.AULAS_TIPO(ID),
    FOREIGN KEY (ID_MODULO) REFERENCES "EDUTECH".DBO.MODULOS(ID)
);

COMMENT ON COLUMN "EDUTECH".DBO.AULAS.ID IS 'Identificador único da aula';
COMMENT ON COLUMN "EDUTECH".DBO.AULAS.TITULO IS 'Título da aula';
COMMENT ON COLUMN "EDUTECH".DBO.AULAS.DURACAO IS 'Duração da aula em minutos';
COMMENT ON COLUMN "EDUTECH".DBO.AULAS.ORDEM IS 'Ordem da aula no módulo';
COMMENT ON COLUMN "EDUTECH".DBO.AULAS.ID_TIPO IS 'Identificador do tipo da aula';
COMMENT ON COLUMN "EDUTECH".DBO.AULAS.ID_MODULO IS 'Identificador do módulo ao qual a aula pertence';


-- CRIACAO DA TABELA DE STATUS DE MATRICULA
CREATE TABLE "EDUTECH".DBO.MATRICULAS_STATUS (
    ID SERIAL PRIMARY KEY NOT NULL,
    STATUS VARCHAR(20) UNIQUE NOT NULL
);

COMMENT ON COLUMN "EDUTECH".DBO.MATRICULAS_STATUS.ID IS 'Identificador único do status da matrícula';
COMMENT ON COLUMN "EDUTECH".DBO.MATRICULAS_STATUS.STATUS IS 'Nome do status da matrícula';


-- CRIACAO DA TABELA DE MATRICULAS
CREATE TABLE "EDUTECH".DBO.MATRICULAS (
    ID SERIAL PRIMARY KEY NOT NULL,
    VALOR_PAGO FLOAT NOT NULL,
    DATA_MATRICULA DATE NOT NULL,
    DATA_CONCLUSAO DATE NULL,
    ID_ALUNO INT NOT NULL,
    ID_CURSO INT NOT NULL,
    ID_STATUS INT NOT NULL,
    FOREIGN KEY (ID_ALUNO) REFERENCES "EDUTECH".DBO.ALUNOS(ID),
    FOREIGN KEY (ID_CURSO) REFERENCES "EDUTECH".DBO.CURSOS(ID),
    FOREIGN KEY (ID_STATUS) REFERENCES "EDUTECH".DBO.MATRICULAS_STATUS(ID)
);

COMMENT ON COLUMN "EDUTECH".DBO.MATRICULAS.ID IS 'Identificador único da matrícula';
COMMENT ON COLUMN "EDUTECH".DBO.MATRICULAS.VALOR_PAGO IS 'Valor pago na matrícula';
COMMENT ON COLUMN "EDUTECH".DBO.MATRICULAS.DATA_MATRICULA IS 'Data da matrícula';
COMMENT ON COLUMN "EDUTECH".DBO.MATRICULAS.DATA_CONCLUSAO IS 'Data de conclusão do curso';
COMMENT ON COLUMN "EDUTECH".DBO.MATRICULAS.ID_ALUNO IS 'Identificador do aluno';
COMMENT ON COLUMN "EDUTECH".DBO.MATRICULAS.ID_CURSO IS 'Identificador do curso';
COMMENT ON COLUMN "EDUTECH".DBO.MATRICULAS.ID_STATUS IS 'Identificador do status da matrícula';


-- CRIACAO DA TABELA DE REGISTRO DE PROGRESSOS NAS AULAS
CREATE TABLE "EDUTECH".DBO.PROGRESSO_AULAS (
    ID SERIAL PRIMARY KEY NOT NULL,
    TEMPO_ASSISTIDO INT DEFAULT 0 NOT NULL,
    CONCLUIDA BOOLEAN DEFAULT FALSE NOT NULL,
    DATA_CONCLUSAO DATE NULL,
    ID_AULA INT NOT NULL,
    ID_MATRICULA INT NOT NULL,
    FOREIGN KEY (ID_AULA) REFERENCES "EDUTECH".DBO.AULAS(ID),
    FOREIGN KEY (ID_MATRICULA) REFERENCES "EDUTECH".DBO.MATRICULAS(ID)
);

COMMENT ON COLUMN "EDUTECH".DBO.PROGRESSO_AULAS.ID IS 'Identificador único do progresso do aluno na aula';
COMMENT ON COLUMN "EDUTECH".DBO.PROGRESSO_AULAS.TEMPO_ASSISTIDO IS 'Tempo assistido da aula em minutos';
COMMENT ON COLUMN "EDUTECH".DBO.PROGRESSO_AULAS.CONCLUIDA IS 'Indica se a aula foi concluída ou não';
COMMENT ON COLUMN "EDUTECH".DBO.PROGRESSO_AULAS.DATA_CONCLUSAO IS 'Data de conclusão da aula';
COMMENT ON COLUMN "EDUTECH".DBO.PROGRESSO_AULAS.ID_AULA IS 'Identificador da aula';
COMMENT ON COLUMN "EDUTECH".DBO.PROGRESSO_AULAS.ID_MATRICULA IS 'Identificador da matrícula do aluno';


-- CRIACAO DA TABELA DE AVALIACOES
CREATE TABLE "EDUTECH".DBO.AVALIACOES (
    ID SERIAL PRIMARY KEY NOT NULL,
    NOTA INT NOT NULL,
    COMENTARIO VARCHAR(500) NULL,
    DATA_AVALIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ID_CURSO INT NOT NULL,
    ID_MATRICULA INT NOT NULL,
    FOREIGN KEY (ID_CURSO) REFERENCES "EDUTECH".DBO.CURSOS(ID),
    FOREIGN KEY (ID_MATRICULA) REFERENCES "EDUTECH".DBO.MATRICULAS(ID),

    CONSTRAINT INTERVALO_NOTA CHECK (NOTA >= 0 AND NOTA <= 5)
);

COMMENT ON COLUMN "EDUTECH".DBO.AVALIACOES.ID IS 'Identificador único da avaliação';
COMMENT ON COLUMN "EDUTECH".DBO.AVALIACOES.NOTA IS 'Nota da avaliação (0 a 5)';
COMMENT ON COLUMN "EDUTECH".DBO.AVALIACOES.COMENTARIO IS 'Comentário da avaliação';
COMMENT ON COLUMN "EDUTECH".DBO.AVALIACOES.DATA_AVALIACAO IS 'Data da avaliação';
COMMENT ON COLUMN "EDUTECH".DBO.AVALIACOES.ID_CURSO IS 'Identificador do curso avaliado';
COMMENT ON COLUMN "EDUTECH".DBO.AVALIACOES.ID_MATRICULA IS 'Identificador da matrícula do aluno que fez a avaliação';


-- CRIACAO DOS INDEXS NAS COLUNAS QUE SAO CHAVES ESTRANGEIRAS NAS TABELAS
CREATE INDEX ON "EDUTECH".DBO.ESPECIALIDADES_INSTRUTORES (ID_ESPECIALIDADE);
CREATE INDEX ON "EDUTECH".DBO.ESPECIALIDADES_INSTRUTORES (ID_INSTRUTOR);
CREATE INDEX ON "EDUTECH".DBO.CURSOS (ID_NIVEL);
CREATE INDEX ON "EDUTECH".DBO.CURSOS (ID_INSTRUTOR);
CREATE INDEX ON "EDUTECH".DBO.CURSOS (ID_CATEGORIA);
CREATE INDEX ON "EDUTECH".DBO.MODULOS (ID_CURSO);
CREATE INDEX ON "EDUTECH".DBO.AULAS (ID_TIPO);
CREATE INDEX ON "EDUTECH".DBO.AULAS (ID_MODULO);
CREATE INDEX ON "EDUTECH".DBO.MATRICULAS (ID_ALUNO);
CREATE INDEX ON "EDUTECH".DBO.MATRICULAS (ID_CURSO);
CREATE INDEX ON "EDUTECH".DBO.MATRICULAS (ID_STATUS);
CREATE INDEX ON "EDUTECH".DBO.PROGRESSO_AULAS (ID_AULA);
CREATE INDEX ON "EDUTECH".DBO.PROGRESSO_AULAS (ID_MATRICULA);
CREATE INDEX ON "EDUTECH".DBO.AVALIACOES (ID_CURSO);
CREATE INDEX ON "EDUTECH".DBO.AVALIACOES (ID_MATRICULA);